#!/bin/sh

load_luckfoxconfig() {
	if [ -f /usr/bin/luckfox-config ]; then
		luckfox-config load
		if [ -f "/usr/bin/luckfox_lvgl_demo" ]; then
			luckfox_lvgl_demo &
		fi
	fi
}

case $1 in
start)
	load_luckfoxconfig
	;;
*)
	exit 1
	;;
esac
